# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Automated Reasoning and Learning
email: ramon.bejar@udl.cat
description: >- # this means to ignore newlines until "baseurl:"
  Slides and lectures notes about automated methods for reasoning and learning in Computer Science
repository: "ramonbejar/razapr" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  ramonbejar

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-readme-index



readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
